name: Rust
permissions:
  contents: read
on:
  push:
    branches: ["main", "add_a_basic_api_server"]
  pull_request:
    branches: ["main", "add_a_basic_api_server"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
